Project_Web_db/Models/Personnel.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Project_Web_db.Models
{
    public class Personnel
    {
        [Key]
        public int id { get; set; }

      
        [Required, EmailAddress, MaxLength(191), Display(Name = "email")]
        public String email { get; set; }

        [Required, MinLength(6), MaxLength(50), DataType(DataType.Password), Display(Name = "password")]
        public String password { get; set; }

        [Required, NotMapped, MinLength(6), MaxLength(50), DataType(DataType.Password), Display(Name = "Confirm password")]
        [Compare("password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }

        public String name { get; set; }

        [DataType(DataType.PhoneNumber), MinLength(10)]
        public String phone_number { get; set; }

        public String provider { get; set; }

        public String state { get; set; }

        public int car_number { get; set; }

        public int status_ban { get; set; }

        public int money { get; set; }

        public DateTime date { get; set; }

        public DateTime date_update { get; set; }
    }
}

Project_Web_db/Models/ViewModel/History_ban_ViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Project_Web_db.Models.ViewModel
{
    public class History_ban_ViewModel
    {
        public string email_user        { get; set; }
        public string name_user         { get; set; }
        public string phone_number_user { get; set; }
        public string state_user        { get; set; }
        public int    status_user       { get; set; }
        public int    command           { get; set; }
        public string name_personnel    { get; set; }
        public string state_personnel   { get; set; }
        public string explanation       { get; set; }
        public DateTime date            { get; set; }

    }
}

Project_Web_db/Controllers/PersonnelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Project_Web_db.Data;
using Project_Web_db.Models;
using Microsoft.AspNetCore.Http;
using Project_Web_db.Models.ViewModel;


// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Project_Web_db.Controllers
{
    [Route("[controller]/[action]")]
    public class PersonnelController : Controller
    {
        private ApplicationDbContext _db;

        public PersonnelController(ApplicationDbContext db)
        {
            _db = db;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }


        public ActionResult Search_userView()
        {
            var query = _db.Users.ToList();

            return View("Search_Account", query);
        }

        [HttpPost]
        public ActionResult Search_user()
        {

            if(Request.Form["Search_ptable"] == "user")
            {

                if (Request.Form["Search_type"] == "email")
                {
                    var query_User = _db.Users.Where(u => u.email == Request.Form["Search"]).ToList();

                        return View("Search_Account", query_User);

                }
                else
                {
                    var query_User = _db.Users.Where(u => u.name == Request.Form["Search"]).ToList();

                    return View("Search_Account", query_User);
                }

            }
            else if(Request.Form["Search_table"] == "personnel")
            {
                if (Request.Form["Search_type"] == "email")
                {
                    var query_Personnel = (from p in _db.Personnels
                                           where (p.email == Request.Form["Search"])
                                           select new User
                                           {
                                               id = p.id,
                                               email = p.email,
                                               name = p.name,
                                               phone_number = p.phone_number,
                                               state = p.state,
                                               money = p.money,
                                               status_ban = p.status_ban

                                           }).ToList();
                    return View("Search_Account", query_Personnel);
                }
                else
                {
                    var query_Personnel = (from p in _db.Personnels
                                           where (p.name == Request.Form["Search"])
                                           select new User
                                           {
                                               id = p.id,
                                               email = p.email,
                                               name = p.name,
                                               phone_number = p.phone_number,
                                               state = p.state,
                                               money = p.money,
                                               status_ban = p.status_ban

                                           }).ToList();
                    return View("Search_Account", query_Personnel);
                }

                
            }
            else
            {
                var query_Personnel = _db.Users.ToList();
                return View("Search_Account", query_Personnel);
            }

        }

        [Route("{email}")]
        public ActionResult Redirect_Search_user(string email)
        {

            
                var query_User = _db.Users.Where(u => u.email == email).ToList();

                var query_Personnel = (from p in _db.Personnels
                                       where (p.email == email)
                                       select new User
                                       {
                                           id = p.id,
                                           email = p.email,
                                           name = p.name,
                                           phone_number = p.phone_number,
                                           state = p.state,
                                           money = p.money,
                                           status_ban = p.status_ban

                                       }).ToList();

                if (query_User != null)
                {
                    return View("Search_Account", query_User);
                }
                else
                {
                    return View("Search_Account", query_Personnel);
                }

        }

        [HttpGet]
        public ActionResult get_profile(string email)
        {
            var query_user = _db.Users.Where(u => u.email == email).FirstOrDefault();

            var query_Personnel = _db.Personnels.Where(p => p.email == email).FirstOrDefault();

            if(query_user != null)
            {
                return Json(query_user);
            }
            else
            {
                return Json(query_Personnel);
            }
            
        }


        [HttpPost]
        public ActionResult Change_ban()
        {
            string email = Request.Form["user_email"];
            int status_user = int.Parse(Request.Form["parse_value_ban"]);


            var query_User = _db.Users.Where(u => u.status_ban == status_user && u.email == email).FirstOrDefault();

            var query_Personnel = _db.Personnels.Where(p => p.status_ban == status_user && p.email == email).FirstOrDefault();

            if (query_User != null)
            {
                if (Request.Form["submit"] == "1")
                {
                    query_User.status_ban = 1;

                    _db.Users.Update(query_User);

  

                    var ban = new Ban
                    {
                        email_user = query_User.email,
                        email_personnel = Request.Cookies["Useremail"],
                        command = 1,
                        explanation = Request.Form["explanation_ban"],
                        date = DateTime.Now
                    };

                    _db.Bans.Add(ban);
                    
                }
                else
                {
                    query_User.status_ban = 0;

                    _db.Users.Update(query_User);

                    var ban = new Ban
                    {
                        email_user = query_User.email,
                        email_personnel = Request.Cookies["Useremail"],
                        command = 0,
                        date = DateTime.Now
                    };

                    _db.Bans.Add(ban);
                }
            }
            else
            {
                if(Request.Form["submit"] == "1")
                {
                    query_Personnel.status_ban = 1;

                    _db.Personnels.Update(query_Personnel);

                    var ban = new Ban
                    {
                        email_personnel_reaction = query_Personnel.email,
                        email_personnel = Request.Cookies["Useremail"],
                        command = 1,
                        explanation = Request.Form["explanation_ban"],
                        date = DateTime.Now
                    };

                    _db.Bans.Add(ban);
                }
                else
                {
                    query_Personnel.status_ban = 0;

                    _db.Personnels.Update(query_Personnel);

                    var ban = new Ban
                    {
                        email_personnel_reaction = query_Personnel.email,
                        email_personnel = Request.Cookies["Useremail"],
                        command = 0,
                        date = DateTime.Now
                    };

                    _db.Bans.Add(ban);
                }
            }
           

            _db.SaveChanges();


            return Redirect($"/Personnel/Redirect_Search_user/{email}");
        }

        [HttpPost]
        public ActionResult addmoney()
        {
            string email_user = Request.Form["user_email"];

            var query_User = _db.Users.Where(u => u.email == email_user).FirstOrDefault();

            var query_Personnel = _db.Personnels.Where(p => p.email == email_user).FirstOrDefault();

          

            if (query_User != null)
            {
               
                    query_User.money = query_User.money + int.Parse(Request.Form["value_money"]);
                    _db.Users.Update(query_User);

                    var create_addmoney = new Personnel_Add_User
                    {
                        email_user = email_user,
                        email_personnel = Request.Cookies["Useremail"],
                        money = int.Parse(Request.Form["value_money"]),
                        date = DateTime.Now
                    };

                    _db.Personnel_Add_Users.Add(create_addmoney);
        
               
            }
            else
            {
                
                    query_Personnel.money = query_Personnel.money + int.Parse(Request.Form["value_money"]);
                    _db.Personnels.Update(query_Personnel);

                    var create_addmoney = new Personnel_Add_User
                    {
                        email_user = email_user,
                        email_personnel = Request.Cookies["Useremail"],
                        money = int.Parse(Request.Form["value_money"]),
                        date = DateTime.Now
                    };

                    _db.Personnel_Add_Users.Add(create_addmoney);

            }

         

Project_Web_db/Views/Personnel/History_ban.cshtml
@model List<History_ban_ViewModel>



<div class="container">

    <div class="row">
        <nav class="navbar navbar-expand-lg navbar-light bg-light media-right">
            <form asp-controller="Personnel" asp-action="Search_History_ban" method="post">

                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav form-inline">

                        <select class="form-control" name="Search_table" id="Search_table" required>
                            <option value="user">User</option>
                            <option value="personnel">Personnel</option>
                        </select>

                        <select class="form-control" name="Search_type" id="Search_type" required>
                            <option value="email">E-Mail</option>
                            <option value="name">Name</option>
                        </select>

                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" id="Search" name="Search" placeholder="Search" aria-label="Search">

                        <button class="btn btn-primary" type="submit">Search</button>

                    </div>
                </div>

            </form>
        </nav>
    </div>

</div>





<table class="customers">
    <thead>
        <tr>
            <th>
                E-mail 
            </th>
            <th>
                Name 
            </th>
            <th>
                Phone Number 
            </th>
            <th>
                State
            </th>
            <th>
                Status
            </th>
            <th>
                Command
            </th>
            <th>
                Name (Personnel)
            </th>
            <th>
                State (Personnel)
            </th>
            <th>
                Description
            </th>
            <th>
                DateTime
            </th>
        </tr>
    </thead>
    <tbody>

        @if (Model.Count() > 0)
        {


            @foreach (var col in Model)
             {
                <tr>

                    <th>
                        @col.email_user
                    </th>

                    <th>
                        @col.name_user
                    </th>

                    <th>
                        @col.phone_number_user
                    </th>

                    <th>
                        @col.state_user

                    </th>

                    <th>
                        @if(col.status_user == 0)
                        {
                            <p>ปกติ</p>

                        }
                        else
                        {

                            <p>โดนบล็อค</p>

                        }
                    </th>

                    <th>
                        @if (col.command == 0)
                        { 
                            <p>ปลดบล็อค</p>
                        }
                        else
                        {

                            <p>บล็อค</p>
                        }
                    </th>

                    <th>
                        @col.name_personnel
                    </th>

                    <th>
                        @col.state_personnel
                    </th>

                    <th>
                        @col.explanation
                    </th>
                    <th>
                        @col.date
                    </th>

                    
                </tr>
             }
        }
        else
        {
            <div class="text1">
                ไม่มีข้อมูล
            </div>
        }

    </tbody>
</table>
<body class="m"></body>

Project_Web_db/Views/Personnel/Personnel_Search_bs.cshtml
@model List<Search_UserIN_busschedule>



<table class="customers">

    <thead>
        <tr>
            <th>
                Passenger
            </th>
            <th>
                E-Mail
            </th>
            <th>
                Phone Member
            </th>
            <th>
                Seat
            </th>
            <th>
                First Station
            </th>
            <th>
                Last Station
            </th>
            <th>
                Date
            </th>
        </tr>
    </thead>

    @if (Model.Count > 0 )
    {
        @foreach (var col in Model)
        {
            <tbody>
                <tr>
                    @if(col.name_user != null)
                    {

                        <td>
                            @col.name_user
                        </td>
                        <td>
                            @col.email_user
                        </td>
                        <td>
                            @col.phone_number_user
                        </td>
                        <td>
                            @col.seat
                        </td>
                        <td>
                            @if(col.first_station == 1)
                            {
                                <p>โพหัก</p>
                            }
                            else if (col.first_station == 2)
                            {
                                <p>คริสเตียน</p>
                            }
                            else if (col.first_station == 3)
                            {
                                <p>บ้านแพ้ว</p>
                            }
                            else if (col.first_station == 4)
                            {
                                <p>โพนิมิต</p>
                            }
                            else if (col.first_station == 5)
                            {
                                <p>สายใต้</p>
                            }
                        </td>
                        <td>
                            @col.traget_station
                        </td>
                        <td>
                            @col.date
                        </td>


                    }
                    else if(col.name_personnel != null)
                    {

                        <td>
                            @col.name_personnel
                        </td>
                        <td>
                            @col.email_personnel
                        </td>
                        <td>
                            @col.phone_number_personnel
                        </td>
                        <td>
                            @col.seat
                        </td>
                        <td>
                            @if (col.first_station == 1)
                            {
                                <p>โพหัก</p>
                            }
                            else if (col.first_station == 2)
                            {
                                <p>คริสเตียน</p>
                            }
                            else if (col.first_station == 3)
                            {
                                <p>บ้านแพ้ว</p>
                            }
                            else if (col.first_station == 4)
                            {
                                <p>โพนิมิต</p>
                            }
                            else if (col.first_station == 5)
                            {
                                <p>สายใต้</p>
                            }
                        </td>
                        <td>
                            @col.traget_station
                        </td>
                        <td>
                            @col.date
                        </td>
                    }
                </tr>
            </tbody>
           
        }
    }
    else
    {
        <div class="text1">
            ไม่มีข้อมูล
        </div>
    }
</table>
<body class="con"></body>