Project_Web_db/Models/ViewModel/Seach_Addmoney_UserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Project_Web_db.Models.ViewModel
{
    public class Search_Addmoney_UserViewModel
    {
        public int id_add { get; set; }
        public string name_user { get; set; }
        public string name_personnel { get; set; }
        public int money { get; set; }
        public DateTime date { get; set; }

    }
}

Project_Web_db/Models/ViewModel/Seach_busscheduleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace Project_Web_db.Models.ViewModel
{
    public class Search_busscheduleViewModel
    {
        public int id { get; set; }

        public int route { get; set; }

        public int station { get; set; }

        public int car_number { get; set; }

        public string time { get; set; }

    }
}

Project_Web_db/Models/ViewModel/Search_busscheduleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace Project_Web_db.Models.ViewModel
{
    public class Search_busscheduleViewModel
    {
        public int id { get; set; }

        public string email_driver { get; set; }

        public int route { get; set; }

        public int station { get; set; }

        public int car_number { get; set; }

        public string phone_number { get; set; }

        public string time { get; set; }

    }
}

Project_Web_db/Controllers/Ticket_personnelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Globalization;
using System.Diagnostics;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Project_Web_db.Models;
using Project_Web_db.Models.AccountViewModels;
using Project_Web_db.Services;
using Project_Web_db.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authentication.Cookies;
using Project_Web_db.Models.ViewModel;


namespace Project_Web_db.Controllers
{

    
    [Route("[controller]/[action]")]
    public class Ticket_personnelController : Controller
    {
        private readonly ApplicationDbContext _db;

        public Ticket_personnelController(ApplicationDbContext db)
        {
            _db = db;
        }


        [HttpGet]
        [Route("{route}/{station}")]
        public async Task<IActionResult> Search_busschedule(int route,int station)
        {


            DateTime timeNow = DateTime.Now;


            if (route == 1 || route == 2)
            {

                var querySchedule = (from bs in _db.Bus_schedules
                                    join personnel in _db.Personnels
                                    on bs.email_personnel equals personnel.email
                                    where (bs.route == route && 
                                           bs.station_set == station && 
                                           bs.date.Date == timeNow.Date)
                                    select new Search_busscheduleViewModel {
                                        id = bs.id ,
                                        email_driver = personnel.email,
                                        time = bs.time,
                                        route = bs.route,
                                        station = bs.station_set,
                                        car_number = personnel.car_number,
                                        phone_number = personnel.phone_number
                                    }).ToList();


                ViewBag.route = route;
                ViewBag.station = station;
                
               if(Request.Cookies["Userstate"] == "Driver")
                {
                    var email = _db.Personnels.Where(p => p.email == Request.Cookies["Useremail"]).FirstOrDefault();

                    var newquerySchedule =  querySchedule.Where(d => d.car_number == email.car_number).Count();


                    ViewBag.check_driver = newquerySchedule;

                  

                    return View("Driver_Search_Busschedule", querySchedule);
                }
               else
                {
                    return View("Search_busschedule", querySchedule);
                }
               
               
            }

                return View("Search_busschedule");

        }

        [HttpGet]
        [Route("{route}/{station}/{alert}")]
        public async Task<IActionResult> Search_busschedule_alert(int route, int station, int alert )
        {


            DateTime timeNow = DateTime.Now;

            if (alert == 1)
            {

                ViewBag.alert = "หมดเวลาการจองในรอบนี้แล้ว กรุณาจองรอบต่อไปครับ";
            }
            else if(alert == 2)
            {
                ViewBag.alert = "ที่นั่งบนรถเต็ม กรุณาจองรอบต่อไปครับ";
            }
            else
            {
                ViewBag.alert = "ระบบขัดข้อง กรุณาจองใหม่อีกครั้งครับ";
            }


            if (route == 1 || route == 2)
            {

                var querySchedule = (from bs in _db.Bus_schedules
                                     join personnel in _db.Personnels
                                     on bs.email_personnel equals personnel.email
                                     where (bs.route == route &&
                                            bs.station_set == station &&
                                            bs.date.Date == timeNow.Date)
                                     select new Search_busscheduleViewModel {
                                         id = bs.id,
                                         time = bs.time,
                                         route = bs.route,
                                         station = bs.station_set,
                                         car_number = personnel.car_number,
                                         phone_number = personnel.phone_number
                                     }).ToList();


                ViewBag.route = route;
                ViewBag.station = station;


                return View("Search_busschedule", querySchedule);
            }

            return View("Search_busschedule");
        }

        [HttpGet]
        [Route("{route}/{station}")]
        public async Task<IActionResult> Create_Bus_busscheduleView(int route, int station)
        {
        

            ViewBag.route = route;
            ViewBag.station = station;


            return View("Create_Bus_busschedule");
        }

        [HttpPost]
        [Route("{route}/{station}")]
        public async Task<IActionResult> Create_Bus_busschedule(int route, int station)
        {
            int count = int.Parse(Request.Form["count"]);
            Debug.WriteLine(count);

            if (route == 1)
            {
                for(int i = 0; i < count; i++)
                {

                    int bus_num = int.Parse(Request.Form[$"bus_number[{i}]"]);


                    var queryPersonnel = _db.Personnels.Where(Ps => Ps.car_number == bus_num).FirstOrDefault();
                    string time = Request.Form[$"time[{i}]"];

                    if (queryPersonnel != null)
                    {
                        
                            var Bus_schedule = new Bus_schedule
                            {
                                email_personnel = queryPersonnel.email,
                                station_set = station,
                                time = time,
                                route = 1,
                                date = DateTime.Now
                            };
                            _db.Bus_schedules.Add(Bus_schedule);
                            _db.SaveChanges();

                          

                       
                    }

                  
                }
               
                return Redirect("/Home/Index");
            }
            else
            {
                for (int i = 0; i < count; i++)
                {

                    int bus_num = int.Parse(Request.Form[$"bus_number[{i}]"]);


                    var queryPersonnel = _db.Personnels.Where(Ps => Ps.car_number == bus_num).FirstOrDefault();
                    string time = Request.Form[$"time[{i}]"];

                    if (queryPersonnel != null)
                    {

                        var Bus_schedule = new Bus_schedule
                        {
                            email_personnel = queryPersonnel.email,
                            station_set = station,
                            time = time,
                            route = 2,
                            date = DateTime.Now
                        };
                        _db.Bus_schedules.Add(Bus_schedule);
                        _db.SaveChanges();




                    }


                }
                return Redirect("/Home/Index");
            }

 
        }

        [HttpGet]
        [Route("{id}")]
        public ActionResult ReservationCreateView(int id)
        {

            var querySchedule = (from bs in _db.Bus_schedules
                                 join personnel in _db.Personnels
                                 on bs.email_personnel equals personnel.email
                                 where (bs.id == id)
                                 select new Search_busscheduleViewModel { id = bs.id, time = bs.time, route = bs.route, station = bs.station_set, car_number = personnel.car_number }).FirstOrDefault();

            var query_reservation = _db.Reservations.Where(r => r.id_bus_schedule == id).Count();

          

            if (querySchedule != null)
            {
                var Hour = querySchedule.time.Split('.')[0];
                var Minute = querySchedule.time.Split('.')[1];

                var timeNow = DateTime.Now;

                DateTime timevalue = new DateTime(timeNow.Year, timeNow.Month, timeNow.Day, int.Parse(Hour), int.Parse(Minute), timeNow.Second);

                int result = DateTime.Compare(timevalue, timeNow);



                 if (result < 0)
                 {
                    return Redirect($"/Ticket_personnel/Search_busschedule_alert/{querySchedule.route}/{querySchedule.station}/1");
                 }
                 else if(query_reservation >= 15)
                 {
                    return Redirect($"/Ticket_personnel/Search_busschedule_alert/{querySchedule.route}/{querySchedule.station}/2");
                 }

            }




            return View("ReservationCreate", querySchedule);
        }

        [HttpPost]
        public ActionResult ReservationCreate()
        {
            var id_request = HttpContext.Session.GetString("UserID");

            var query_user = _db.Users.Where(u => u.id == int.Parse(id_request)).FirstOrDefault();
            var query_personnel = _db.Personnels.Where(u => u.id == int.Parse(id_request)).FirstOrDefault();



            if (query_user != null)
            {
                string email = query_user.email;

                var reservations = new Reservations
                {
                    email_user_ticket = email,
                    id_bus_schedule = int.Parse(Request.Form["id_bus"]),

Project_Web_db/Views/Ticket_personnel/Create_Bus_busschedule.cshtml
@model IEnumerable<Project_Web_db.Models.Bus_schedule>

<body class="con">
    <div class="container">
        <div class="row">

            <form asp-controller="Ticket_personnel" asp-action="Create_Bus_busschedule" method="Post">
                <table class="customers">
                    <thead>
                        <tr>
                            <th class="textcolor">
                                รอบที่
                            </th>
                            <th>
                                หมายเลขรถ
                            </th>
                            <th >
                                เวลา
                            </th>
                        </tr>

                    <tbody style="color: brown" id="row"></tbody>
                </table>
                
                <input type="hidden" id="count" name="count" value="0" />
                <button  type="submit" class="btn btn-primary" style=" position: fixed; align-items:center; left:45%;">OK</button>
            </form>

            <button type="button"  class="btn btn-primary" style=" position: fixed; align-items:center; left:50%;  " name="button" onclick="onAddClick()">ADD</button>

        </div>
    </div>
</body>
<script>
    window.onload = function ()
    {
        onAddClick();

    }
      function onAddClick()
      {
        var c = document.getElementById('count');
        var r = document.getElementById('row');

        var index = +c.value;

        var tr = '<tr>\
                                <td>'+ (index + 1) +'</td>\
                                <td>\
                                    <select class= "form-control form-control-lg" style="width: 150px;margin-left: 35%;"  name="bus_number['+ index + ']" id="bus_number[' + index +']">\
                                        <option value="1">1</option>\
                                        <option value="2">2</option>\
                                        <option value="3">3</option>\
                                        <option value="4">4</option>\
                                        <option value="5">5</option>\
                                        <option value="6">6</option>\
                                        <option value="7">7</option>\
                                        <option value="8">8</option>\
                                        <option value="9">9</option>\
                                        <option value="10">10</option>\
                                    </select>\
                                </td>\
                                <td>\
                                    <select class="form-control form-control-lg" style="width: 150px;margin-left: 35%;" name="time['+ index + ']" id="time[' + index +']">\
                                        <option value="5.00">5.00</option>\
                                        <option value="5.15">5.15</option>\
                                        <option value="5.30">5.30</option>\
                                        <option value="5.45">5.45</option>\
                                        <option value="6.00">6.00</option>\
                                        <option value="6.15">6.15</option>\
                                        <option value="6.30">6.30</option>\
                                        <option value="6.45">6.45</option>\
                                        <option value="7.00">7.00</option>\
                                        <option value="7.15">7.15</option>\
                                        <option value="7.30">7.30</option>\
                                        <option value="7.45">7.45</option>\
                                        <option value="8.00">8.00</option>\
                                        <option value="8.15">8.15</option>\
                                        <option value="8.30">8.30</option>\
                                        <option value="8.45">8.45</option>\
                                        <option value="9.00">9.00</option>\
                                        <option value="9.15">9.15</option>\
                                        <option value="9.30">9.30</option>\
                                        <option value="9.45">9.45</option>\
                                        <option value="10.00">10.00</option>\
                                        <option value="10.15">10.15</option>\
                                        <option value="10.30">10.30</option>\
                                        <option value="10.45">10.45</option>\
                                        <option value="11.00">11.00</option>\
                                        <option value="11.15">11.15</option>\
                                        <option value="11.30">11.30</option>\
                                        <option value="11.45">11.45</option>\
                                        <option value="12.00">12.00</option>\
                                        <option value="12.15">12.15</option>\
                                        <option value="12.30">12.30</option>\
                                        <option value="12.45">12.45</option>\
                                        <option value="13.00">13.00</option>\
                                        <option value="13.15">13.15</option>\
                                        <option value="13.30">13.30</option>\
                                        <option value="13.45">13.45</option>\
                                        <option value="14.00">14.00</option>\
                                        <option value="14.15">14.15</option>\
                                        <option value="14.30">14.30</option>\
                                        <option value="14.45">14.45</option>\
                                        <option value="15.00">15.00</option>\
                                        <option value="15.15">15.15</option>\
                                        <option value="15.30">15.30</option>\
                                        <option value="15.45">15.45</option>\
                                        <option value="16.00">16.00</option>\
                                        <option value="16.15">16.15</option>\
                                        <option value="16.30">16.30</option>\
                                        <option value="16.45">16.45</option>\
                                        <option value="17.00">17.00</option>\
                                        <option value="17.15">17.15</option>\
                                        <option value="17.30">17.30</option>\
                                        <option value="17.45">17.45</option>\
                                        <option value="18.00">18.00</option>\
                                        <option value="18.15">18.15</option>\
                                        <option value="18.30">18.30</option>\
                                        <option value="18.45">18.45</option>\
                                        <option value="19.00">19.00</option>\
                                        <option value="19.15">19.15</option>\
                                        <option value="19.30">19.30</option>\
                                        <option value="19.45">19.45</option>\
                                        <option value="20.00">20.00</option>\
                                        <option value="20.15">20.15</option>\
                                        <option value="20.30">20.30</option>\
                                    </select>\
                                </td>\
                            </tr>';

        r.innerHTML += tr;
        c.value = index + 1;
      }
</script>

    

Project_Web_db/Views/Ticket_personnel/Driver_Search_Busschedule.cshtml
@using System.Collections.Generic
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Mvc
@using Microsoft.AspNetCore.Identity
@using Project_Web_db.Models




@model List<Search_busscheduleViewModel>

<div class="container body-content">

    <input type="hidden" id="popup" value="@ViewBag.alert" />


    @if (ViewBag.route == 1)
    {

        <nav class="nav padbar">
            <div>
                <ul class="nav ul1">
                    <li class="li1">
                        <a href='@Url.Action("Search_busschedule", "Ticket_personnel", new {route = 1, station = 1})'>
                            โพหัก
                        </a>
                    </li>
                    <li class="li1">
                        <a href='@Url.Action("Search_busschedule", "Ticket_personnel", new {route = 1, station = 2 })'>
                            คริสเตียน
                        </a>
                    </li>
                    <li class="li1">
                        <a href='@Url.Action("Search_busschedule", "Ticket_personnel", new {route = 1, station = 3 })'>
                            บ้านแพ้ว
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    }
    else
    {

        <nav class="nav padbar">
            <div>
                <ul class="nav ul1">
                    <li class="li1">
                        <a href="@Url.Action("Search_busschedule", "Ticket_personnel", new {route = 2, station = 5})">
                            สายใต้
                        </a>
                    </li>

                    <li class="li1">
                        <a href="@Url.Action("Search_busschedule", "Ticket_personnel", new {route = 2, station = 4})">
                            โพนิมิตร
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    }


    @if (Model.Count() != 0 )
    {


        if(ViewBag.check_driver > 0)
        {
              <input type="hidden" id="state" value="@Context.Session.GetString("Userstate").ToString()" />

        <table class="customers">
            <thead>
                <tr>
                    <th>หมายเลขรถ</th>
                    <th>เบอร์ติดต่อ</th>
                    <th>เวลา</th>
                    <th>
                        ดูผู้โดยสาร
                    </th>


                </tr>
            </thead>

            <tbody>
                @{int index = 0;}
                @foreach (var col in Model)
                {
                    @if (col.email_driver == Context.Session.GetString("Useremail"))
                    {
                        <input type="hidden" id="id_@index" value="@col.id" />
                        <input type="hidden" id="time_@index" value="@col.time" />


                            <tr>
                                <td>@col.car_number</td>
                                <td>@col.phone_number</td>
                                <td>@col.time</td>

                                <td>
                                    <button class="btn btn-success" onclick="location.href='@Url.Action("Check_userInschedule", "Personnel", new { id = col.id })'">รายละเอียดการจอง</button>
                                </td>

                            </tr>

                    }



                    index++;
                }
            </tbody>


        </table>

        }
        else
        {
            <p class="text1">ไม่มีรอบรถที่คุณต้องวิ่ง</p>

        }
      
     }
    else 
    {
        <div class="text1">
            ระบบยังไม่พร้อมใช้งาน
            กรุณารอเจ้าหน้าที่เปิดทำการ
        </div>

    }




</div>

Project_Web_db/Views/Ticket_personnel/Seach_Addmoney_User.cshtml
@using Microsoft.AspNetCore.Http

@model List<Search_Addmoney_UserViewModel>

<table class="table">
    <thead>
        <tr>
            <th>ผู้รับ</th>
            <th>ดำเนินการโดย</th>
            <th>เงินที่ได้รับ</th>
            <th>วัน-เวลา</th>

        </tr>
    </thead>

    @if (Model.Count > 0)
    {
        <tbody>
            @foreach (var col in Model)
            {


                <tr>
                    <td>@col.name_user</td>
                    <td>@col.name_personnel</td>
                    <td>@col.money</td>
                    <td>@col.date</td>


                </tr>


            }
        </tbody>

    }
    else
    {
        <p>ไม่มีข้อมูลในระบบ</p>

    }



</table>